# There are no constraints in this XDC file, because
#
# (a) the only clock in the system is generated by the processor part, and
#     it's already constrained through generated XDCs, and
# (b) there are no pin placements, since the board has nothing connected to
#     the PL pins, except for general-purpose expansion connectors.


set_property IOSTANDARD LVCMOS25 [get_ports {DATA_IMAGE[9]}]
set_property IOSTANDARD LVCMOS25 [get_ports {DATA_IMAGE[8]}]
set_property IOSTANDARD LVCMOS25 [get_ports {DATA_IMAGE[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {DATA_IMAGE[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {DATA_IMAGE[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {DATA_IMAGE[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {DATA_IMAGE[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {DATA_IMAGE[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {DATA_IMAGE[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {DATA_IMAGE[0]}]
set_property PACKAGE_PIN R19 [get_ports {DATA_IMAGE[9]}]
set_property PACKAGE_PIN T11 [get_ports {DATA_IMAGE[8]}]
set_property PACKAGE_PIN T12 [get_ports {DATA_IMAGE[7]}]
set_property PACKAGE_PIN T10 [get_ports {DATA_IMAGE[6]}]
set_property PACKAGE_PIN T19 [get_ports {DATA_IMAGE[5]}]
set_property PACKAGE_PIN U12 [get_ports {DATA_IMAGE[4]}]
set_property PACKAGE_PIN V12 [get_ports {DATA_IMAGE[3]}]
set_property PACKAGE_PIN U13 [get_ports {DATA_IMAGE[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports FRAME_VALID]
set_property IOSTANDARD LVCMOS33 [get_ports INT_TIME1]
set_property IOSTANDARD LVCMOS33 [get_ports INT_TIME2]
set_property IOSTANDARD LVCMOS33 [get_ports INT_TIME3]
set_property IOSTANDARD LVCMOS25 [get_ports LINE_VALID]
set_property IOSTANDARD LVCMOS33 [get_ports LUPA_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports LUPA_RST]
set_property IOSTANDARD LVCMOS25 [get_ports SPI_CLK]
set_property IOSTANDARD LVCMOS25 [get_ports SPI_DAT]
set_property IOSTANDARD LVCMOS25 [get_ports SPI_EN]
set_property PACKAGE_PIN C20 [get_ports LUPA_RST]
set_property PACKAGE_PIN D20 [get_ports LUPA_CLK]
set_property PACKAGE_PIN P14 [get_ports FRAME_VALID]
set_property PACKAGE_PIN T15 [get_ports LINE_VALID]


set_property PACKAGE_PIN Y16 [get_ports SPI_EN]
set_property PACKAGE_PIN W14 [get_ports SPI_CLK]
set_property PACKAGE_PIN Y17 [get_ports SPI_DAT]


set_property IOSTANDARD LVCMOS25 [get_ports {LED_debug[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LED_debug[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LED_debug[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LED_debug[0]}]


set_property PACKAGE_PIN B19 [get_ports INT_TIME1]


set_property PACKAGE_PIN B20 [get_ports INT_TIME2]
set_property PACKAGE_PIN A20 [get_ports INT_TIME3]





set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets FRAME_VALID_IBUF]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets LINE_VALID_IBUF]
















set_property PULLUP true [get_ports LINE_VALID]
set_property PULLUP true [get_ports FRAME_VALID]




















set_property PULLUP true [get_ports SPI_CLK]
set_property PULLUP true [get_ports SPI_DAT]
set_property PULLUP true [get_ports SPI_EN]


set_property PACKAGE_PIN T16 [get_ports {LED_debug[0]}]
set_property PACKAGE_PIN V15 [get_ports {LED_debug[1]}]
set_property PACKAGE_PIN U17 [get_ports {LED_debug[2]}]
set_property PACKAGE_PIN W15 [get_ports {LED_debug[3]}]
